pileup_reweight_direct : &central_pu "
0, 0.360609416811339, 0.910848525427002, 1.20629960507795, 0.965997726573782, 1.10708082813183, 1.14843491548622, 0.786526251164482, 0.490577792661333, 0.740680941110478,
0.884048630953726, 0.964813189764159, 1.07045369167689, 1.12497267309738, 1.17367530613108, 1.20239808206413, 1.20815108390021, 1.20049333094509, 1.18284686347315, 1.14408796655615,
1.0962284704313, 1.06549162803223, 1.05151011089581, 1.05159666626121, 1.05064452078328, 1.0491726301522, 1.05772537082991, 1.07279673875566, 1.0837536468865, 1.09536667397119,
1.10934472980173, 1.09375894592864, 1.08263679568271, 1.04289345879947, 0.9851490341672, 0.909983816540809, 0.821346330143864, 0.71704523475871, 0.609800913869359, 0.502935245638477,
0.405579825620816, 0.309696044611377, 0.228191137503131, 0.163380359253309, 0.113368437957202, 0.0772279997453792, 0.0508111733313502, 0.0319007262683943, 0.0200879459309245, 0.0122753366005436,
0.00739933885813127, 0.00437426967257811, 0.00260473545284139, 0.00157047254226743, 0.000969500595715493, 0.000733193118123283, 0.000669817107713128, 0.000728548958604492, 0.000934559691182011, 0.00133719688378802,
0.00186652283903214, 0.00314422244976771, 0.00406954793369611, 0.00467888840511915, 0.00505224284441512, 0.00562827194936864, 0.0055889504870752, 0.00522867039470319, 0.00450752163476433, 0.00395300774604375,
0.00330577167682956, 0.00308353042577215, 0.00277846504893301, 0.00223943190687725, 0.00196650068765464, 0.00184742734258922, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0 "
pileup_reweight_direct_down : "
0, 0.37361294640242, 1.1627791004568, 1.26890787896295, 1.10266790442705, 1.23456697093644, 1.26278991594152, 0.909648777562084, 0.759569490571151, 1.09035651921682,
1.34530547603283, 1.48713160105, 1.52535976889483, 1.49730550773404, 1.49792998045778, 1.49767851097519, 1.44431045398336, 1.3681909492045, 1.29912252494785, 1.2274279217797,
1.16525969099909, 1.12531044676724, 1.09094501417685, 1.06405434433422, 1.03997120824565, 1.0185716022098, 1.00560949501652, 0.997570939806059, 0.985543761409897, 0.972557804582185,
0.957832827239337, 0.9139572640153, 0.872252387173971, 0.808388185417578, 0.733817960498049, 0.650440963845892, 0.561688505024782, 0.466564380334112, 0.374428618658619, 0.28845274688129,
0.214909665968644, 0.149991974352384, 0.100014138338029, 0.0642260884603397, 0.0396553405911344, 0.0238687936736627, 0.0137921542898078, 0.00756854010632403, 0.00415483516246187, 0.00221776872027937,
0.00118249725637452, 0.000641889697310868, 0.000383647166012176, 0.000273637590071334, 0.000242902582071058, 0.000291239677209452, 0.000394091114279828, 0.000542541231466254, 0.000771067920964491, 0.00113596447675107,
0.00158061353194779, 0.00261959852500539, 0.00331800452823827, 0.00372426930370732, 0.00392086545082614, 0.00425479965493548, 0.00411256966391362, 0.00374240422174387, 0.00313603438166934, 0.00267155793176928,
0.00216878198028599, 0.00196249821290853, 0.00171433839159669, 0.00133866519755926, 0.00113810604240254, 0.00103447940224886, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0 "
pileup_reweight_direct_up   : "
0, 0.351377216124927, 0.717199649125846, 1.14121536968772, 0.84885826611733, 1.00700929402897, 1.03428595270903, 0.717444379696992, 0.344078389355127, 0.499570875027422,
0.606614916257104, 0.632584599390169, 0.731450949466174, 0.827511723989754, 0.910682115553867, 0.960170981598162, 0.988896170761361, 1.02468865580207, 1.05296667126403, 1.05112033565679,
1.0269129153969, 1.00548641752714, 0.998316130432865, 1.01492587998551, 1.03753749807849, 1.05742218946485, 1.08503978097083, 1.12134132247053, 1.15585339474274, 1.19214399856171,
1.23308400947467, 1.24528804633732, 1.26786364716917, 1.26101551498967, 1.23297806722714, 1.18042533075471, 1.10534683838101, 1.00275591661645, 0.889094305531985, 0.768791254270252,
0.655054015673457, 0.533361034358457, 0.423095146361996, 0.329177839117034, 0.250352385505809, 0.188377378855567, 0.137852651411779, 0.0968577167707531, 0.0686240187247059, 0.0473889635126706,
0.0323695027438475, 0.0216752397914914, 0.0145119352923332, 0.00961177893634792, 0.00615582219138384, 0.00430085627914427, 0.00305735512896403, 0.00223567790438986, 0.00189369737638594, 0.00199585978316291,
0.00236236592656064, 0.00372472999463276, 0.00474687312579969, 0.00549508151576102, 0.00603023110946686, 0.0068545111910253, 0.00695838760530896, 0.00666224781277046, 0.00588243140681038, 0.00528714370892014,
0.00453424615273565, 0.00433985030329723, 0.00401493171035719, 0.00332436608713241, 0.00300063798808221, 0.00289925128977536, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0 "
elHLT_MC     : "HLT_Ele27_WPTight_Gsf_v7"
elHLT_Data   : "HLT_Ele27_WPTight_Gsf_v*"
muHLT_MC1    : "HLT_IsoMu24_v4"
muHLT_MC2    : "HLT_IsoTkMu24_v4"
muHLT_Data1  : "HLT_IsoMu24_v*"
muHLT_Data2  : "HLT_IsoTkMu24_v*"
jetHLT       : "HLT_PFJet140_v"
withTauIDSFs : False
muon_effs       : '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/analysis/muon-effs/'
electron_effs   : '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/analysis/electron-effs/'
muscleDir    :     '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/data/jec/'
jecDir       :     '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/data/jec/25ns/'
resolutionFile  :  '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/data/jec/25ns/Spring16_25nsV10_MC_PtResolution_AK4PFchs.txt'
scaleFactorFile :  '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/data/jec/25ns/Spring16_25nsV10_MC_SF_AK4PFchs.txt'
dataDriven_tauFakeRates1 :          '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/jobing/configs/jet_to_tau_fakerates1.root'
dataDriven_tauFakeRates2 :          '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/jobing/configs/jet_to_tau_fakerates2.root'
dataDriven_tauFakeRates_dileptons : '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/jobing/configs/jet_to_tau_fakerates_dileptons.root'
bTaggingEfficiencies          :     '${CMSSW_BASE}/src/UserCode/ttbar-leptons-80X/jobing/configs/b-tagging-efficiencies.root'
tau_fake_rate_histo1_fraction : 0.5
tau_decayMode       : "decayModeFinding"
tau_ID              : "byMediumCombinedIsolationDeltaBetaCorr3Hits"
tau_againstMuon     : "againstMuonTight3"
tau_againstElectron : "againstElectronTightMVA6"
tau_Loose_ID         : "byLooseCombinedIsolationDeltaBetaCorr3Hits"
tau_Tight_ID         : "byTightIsolationMVArun2v1DBoldDMwLT"
jetID   : "Loose"
jetPUID : "TightPU"
with_PU: False
jet_kino_cuts_pt    : 25.
jet_kino_cuts_eta   : 2.4
tau_kino_cuts_pt    : 25.
tau_kino_cuts_eta   : 2.3
jettaufr_jet_kino_cuts_pt    : 20.
jettaufr_jet_kino_cuts_eta   : 2.4
jettaufr_tau_kino_cuts_pt    : 20.
jettaufr_tau_kino_cuts_eta   : 2.3
conf_record_electrons:  False
conf_record_muons:      False
conf_record_taus_ID:    False
conf_record_taus_kino:  False
